In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
dfcoaches = pd.read_json('coaches.json',encoding='utf-8')
dfplayers = pd.read_json('players.json',encoding='utf-8')
dfteams = pd.read_json('teams.json',encoding='utf-8')
dfevents = pd.read_json('events_England.json',encoding='utf-8')
dfmatches = pd.read_json('matches_England.json',encoding='utf-8')

In [3]:
#Distinguishing HOME,AWAY teams for each match and result of match.

hometeams = []
homeresult = []
awayteams = []
awayresult = []

for index,row in dfmatches.iterrows():
    a,b,c,d = row['label'].replace('-',',').split(',')
    hometeams.append(a)
    awayteams.append(b)
    if int(c)>int(d):
        homeresult.append('win')
        awayresult.append('lose')
    elif int(c)<int(d):
        awayresult.append('win')
        homeresult.append('lose')
    else:
        awayresult.append('draw')
        homeresult.append('draw')

In [4]:
#Adding needed columns for our test to the dataframe of Mtaches. 

dfmatches['hometeams'] = hometeams
dfmatches['awayteams'] = awayteams
dfmatches['homeresult'] = homeresult
dfmatches['awayresult'] = awayresult

In [5]:
dfmatches.head()

competitionId                              date              dateutc  \
0            364  May 13, 2018 at 4:00:00 PM GMT+2  2018-05-13 14:00:00   
1            364  May 13, 2018 at 4:00:00 PM GMT+2  2018-05-13 14:00:00   
2            364  May 13, 2018 at 4:00:00 PM GMT+2  2018-05-13 14:00:00   
3            364  May 13, 2018 at 4:00:00 PM GMT+2  2018-05-13 14:00:00   
4            364  May 13, 2018 at 4:00:00 PM GMT+2  2018-05-13 14:00:00   

  duration  gameweek                                         label  \
0  Regular        38              Burnley - AFC Bournemouth, 1 - 2   
1  Regular        38  Crystal Palace - West Bromwich Albion, 2 - 0   
2  Regular        38            Huddersfield Town - Arsenal, 0 - 1   
3  Regular        38     Liverpool - Brighton & Hove Albion, 4 - 0   
4  Regular        38            Manchester United - Watford, 1 - 0   

                                            referees  roundId  seasonId  \
0  [{'refereeId': 385705, 'role': 'referee'}, {'r...  4405654    181150   
1  [{'refereeId': 381851, 'role': 'referee'}, {'r...  4405654    181150   
2  [{'refereeId': 384965, 'role': 'referee'}, {'r...  4405654    181150   
3  [{'refereeId': 385704, 'role': 'referee'}, {'r...  4405654    181150   
4  [{'refereeId': 381853, 'role': 'referee'}, {'r...  4405654    181150   

   status                                          teamsData  \
0  Played  {'1646': {'scoreET': 0, 'coachId': 8880, 'side...   
1  Played  {'1628': {'scoreET': 0, 'coachId': 8357, 'side...   
2  Played  {'1609': {'scoreET': 0, 'coachId': 7845, 'side...   
3  Played  {'1651': {'scoreET': 0, 'coachId': 8093, 'side...   
4  Played  {'1644': {'scoreET': 0, 'coachId': 93112, 'sid...   

                      venue  winner     wyId           hometeams  \
0                 Turf Moor    1659  2500089            Burnley    
1             Selhurst Park    1628  2500090     Crystal Palace    
2  The John Smith's Stadium    1609  2500091  Huddersfield Town    
3                   Anfield    1612  2500092          Liverpool    
4              Old Trafford    1611  2500093  Manchester United    

                 awayteams homeresult awayresult  
0          AFC Bournemouth       lose        win  
1     West Bromwich Albion        win       lose  
2                  Arsenal       lose        win  
3   Brighton & Hove Albion        win       lose  
4                  Watford        win       lose

In [18]:
#collecting teams playing in PL of England.

print(set(dfmatches['hometeams']))

{'Leicester City ', 'Southampton ', 'Burnley ', 'Brighton & Hove Albion ', 'Watford ', 'Stoke City ', 'West Ham United ', 'Tottenham Hotspur ', 'Chelsea ', 'AFC Bournemouth ', 'Arsenal ', 'West Bromwich Albion ', 'Newcastle United ', 'Manchester City ', 'Everton ', 'Swansea City ', 'Huddersfield Town ', 'Liverpool ', 'Crystal Palace ', 'Manchester United '}


In [19]:
#Selecting 5 teams for doing the test.

selected_teams = ['Manchester United', 'Watford', 'Liverpool', 'Crystal Palace', 'Chelsea']
# results = dict.fromkeys(selected_teams,[0]*6)
results=np.zeros((5,6), dtype=int)

In [20]:
#calculating No. of WIN,LOSE and DRAW of selected teams in the season.

for index,row in dfmatches.iterrows():
    for i in range(0,5):
        
        if (str(dfmatches['hometeams'][index]).strip() == selected_teams[i]):
            if (str(dfmatches['homeresult'][index]).strip() == 'win'):
                results[i][0] +=1
            if (str(dfmatches['homeresult'][index]).strip() == 'draw'):
                results[i][1] +=1
            if (str(dfmatches['homeresult'][index]).strip() == 'lose'):
                results[i][2] +=1
        if (str(dfmatches['awayteams'][index]).strip() == selected_teams[i]):
            if (str(dfmatches['awayresult'][index]).strip() == 'win'):
                results[i][3] +=1
            if (str(dfmatches['awayresult'][index]).strip() == 'draw'):
                results[i][4] +=1
            if (str(dfmatches['awayresult'][index]).strip() == 'lose'):
                results[i][5] +=1

In [10]:
print(results)

[[15  2  2 10  4  5]
 [ 7  6  6  4  2 13]
 [12  7  0  9  5  5]
 [ 7  5  7  4  6  9]
 [11  4  4 10  3  6]]


In [22]:
#Building Contingency table for selected teams.

contin_table = pd.DataFrame(results, columns = ['homewin', 'homedraw', 'homelose', 'awaywin', 'awaydraw', 'awaylose'], index=selected_teams)
contin_table

homewin  homedraw  homelose  awaywin  awaydraw  awaylose
Manchester United       15         2         2       10         4         5
Watford                  7         6         6        4         2        13
Liverpool               12         7         0        9         5         5
Crystal Palace           7         5         7        4         6         9
Chelsea                 11         4         4       10         3         6

In [23]:
#Doing Chi square test.

stats.chi2_contingency(contin_table)

(30.261197432250068,
 0.0657304343872097,
 20,
 array([[10.4,  4.8,  3.8,  7.4,  4. ,  7.6],
        [10.4,  4.8,  3.8,  7.4,  4. ,  7.6],
        [10.4,  4.8,  3.8,  7.4,  4. ,  7.6],
        [10.4,  4.8,  3.8,  7.4,  4. ,  7.6],
        [10.4,  4.8,  3.8,  7.4,  4. ,  7.6]]))

## Hypothsis Test - Chi Square Test

#### H0 is the hypothesis that there is no differnece between result of a match for a team if that team is on home or away side.
#### H1 is the hypothesis that there is differnece in a team's performance when that is on home or away side. 
#### Rejecting threshold for doing this test is supposed to be 0.05.
#### Selected teams for analysis are as follow: {Manchester United, Watford, Liverpool, Crystal Palace, Chelsea}

## Result

### As obtained P-value (0.06) is greater than 0.05, so we can not reject H0 . so by this observations we can say H0 is True.